[package]
name = "grepedit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.6"
crossterm = "0.24.0"
simple-log = "1.6.0"
tui = "0.18.0"

